# imports
import = ["/home/noir/.cache/wal/colors-alacritty.toml"]

# define defualt shell
shell = "/usr/bin/fish"

[env]
TERM = "tmux-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 10

[window]
padding = { x = 5, y = 5 }
dynamic_padding = false
decorations = "None"
