# define defualt shell
shell = "/usr/bin/fish"

[env]
TERM = "tmux-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 12

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "None"
opacity = 0.98
